### PR TITLE
fix #215

### LINKED ISSUE #215: mouse over notes not working on scrolled texts
while testing https://github.com/alpheios-project/alpheios_nemo_ui/issues/47, I come across an issue with notes not being displayed on mouse over.
go to https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi045.perseus-lat1/passage/1.31-1.35
if you use the browse passage option or the arrows on top nav to browse through pages, mouse over on notes works fine. when I use the scrolling bar to go forward in the text, the mouse over does not work anymore in the text that has been displayed by the scrolling action, it does work in the text that was already there.

### PR DESCRIPTION
**Pull request by balmas**
scrolled passages need to be updated with popover handler for notes

### CODE REVIEW

File: alpheios_nemo_ui/data/assets/js/text.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
...
-    $(this).popover({
-      html: true,
-      content: function() {
-        return $(this).next('.popover-content').html();
-      }
-    });
-  });
+  $("[data-toggle=popover]").each(showNotes)
 });
+
```
Comment (irina060981) [inline alpheios_nemo_ui/data/assets/js/text.js]: @balmas , I tried to find the difference between the code  (except that it was moved to the external function) and failed! 
could you help me and tell - what exactly it should fix?
when we scroll and add new passages - it doesn't add popover handler to new added ones?

**Comment by balmas** [comment]
@irina060981 what do you think? any objections to my merging this?
